version: "3.3"

services:
  pg:
    image: postgres:11.5-alpine
    container_name: pg-database
    env_file:
      - ./api/.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - redePostgres

  dev-api:
    image: joaomede/nodejs12prod:1.0
    container_name: "dev-api"
    ports:
      - 8081:80
    expose:
      - 8081
    depends_on:
      - pg
    links:
      - pg
    environment:
      HOSTDB: pg
    env_file:
      - ./api/.env
    command: > 
      bash -c "./scripts/dev.sh"
    volumes:
      - ./api:/usr/src/app/api
      - ./scripts:/usr/src/app/scripts
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - redePostgres
  
  dev-view:
    image: joaomede/nodejs12prod:1.0
    container_name: "dev-view"
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - dev-api
    links:
      - dev-api
    command: yarn dev:pwa
    volumes:
      - ./view:/usr/src/app
    networks:
      - redePostgres

networks:
  redePostgres:
    driver: bridge
