name: CI

on:
  # push:
  #   branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x]
    defaults:
      run:
        shell: bash
        working-directory: ./tests

    steps:
      - uses: actions/checkout@v2
        # name: Use Node.js ${{ matrix.node-version }}
        name: Use Node.js 12x

      - uses: actions/setup-node@v1
        name: Project Install
        # with:
        #   node-version: ${{ matrix.node-version }}
        with:
          node-version: '12.x'
      - run: npm install --production
        # env: 
        #   PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'false'

      # - uses: mujo-code/puppeteer-headful@12.3.1
      - uses: ./
        name: Tests e2e
      - run: yarn test:e2e
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          URL: ${{ secrets.URL }}
          CI: 'true'
          PUPPETEER_EXEC_PATH: '/usr/bin/google-chrome'
